name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
    - run: nimble install -y libcurl
    - run: nimble install -y zippy
    - run: nim c tests/debug_server.nim
    - run: nimble test -y
    - run: nimble test --gc:arc -y
